CREATE TABLE IF NOT EXISTS type_table(id IDENTITY PRIMARY KEY, number BOOLEAN, lower_case BOOLEAN, upper_case BOOLEAN, exception VARCHAR(255));
CREATE TABLE IF NOT EXISTS serial_table(id IDENTITY PRIMARY KEY, value VARCHAR(255), set_id INTEGER);
CREATE TABLE IF NOT EXISTS set_table(id IDENTITY PRIMARY KEY, name VARCHAR(255), created TIMESTAMP, type_id INTEGER);
